# ----------------------------------------------------------------------------------------
#
#   Jupyterlab setup 
#
#   Jupyter Lab - http://localhost:8888
#   Tensorboard - http://localhost:6006
#
# ----------------------------------------------------------------------------------------
version: "3"

services:
  # run jupyterlab on a local port 8888
  # without any authentication
  jupyterlab:
    container_name: jupyterlab
    hostname: jupyterlab
    image: stellars/stellars-jupyterlab-ds:latest
    build:
       context: build
       dockerfile: Dockerfile
    command: /start-jupyter.sh
    working_dir: /mnt/workspace
    ports:
       - 8888:8888 # jupyterlab
       - 6006:6006 # tensorboard
    volumes:
      - ./home:/mnt/home:ro   # copying files from 'home' directory to target home directory
      - ./home/.jupyter:/home/jupyterlab/.jupyter:rw  # jupyter settings, making sure it is synced
      - ./workspace:/mnt/workspace:rw      # this maps your projects folder
      # - ../../projects:/mnt/workspace:rw # example: local mapping (stellars)

# EOF
