# ----------------------------------------------------------------------------------------
#
#   Jupyterlab setup 
#
#   Jupyter Lab - http://localhost:8888
#   Tensorboard - http://localhost:6006
#
# ----------------------------------------------------------------------------------------
version: "3"

services:
  # run jupyterlab on a local port 8888
  # without any authentication
  jupyterlab:
    container_name: jupyterlab
    hostname: jupyterlab
    image: stellars/stellars-jupyterlab-ds:latest
    build:
       context: build
       dockerfile: Dockerfile
    command: /start-jupyterlab.sh
    ports:
       - 8888:8888 # jupyterlab
       - 8000:8000 # jupyterhub
       - 8001:8001 # jupyterhub proxy
       - 6006:6006 # tensorboard
       - 5000:5000 # mlflow
    volumes:
      - home:/home/lab:rw   # jupyterlab user directory persistence
      - workspace:/mnt/workspace:rw  # user projects workspace volume persistence
      - certs:/mnt/certs:rw  # persistent certificate store for ssl

volumes:
  workspace:
  certs:
  home:

# EOF
