# ----------------------------------------------------------------------------------------
#
#   Jupyter Lab - http://localhost:8888
#   Tensorboard - http://localhost:6006
#
# ----------------------------------------------------------------------------------------
version: "3"

services:
  # run jupyterlab on a local port 8888
  # without any authentication
  jupyterlab:
    container_name: jupyterlab
    hostname: stellars-jupyterlab-ds
    image: stellars/stellars-jupyterlab-ds:latest
    build:
       context: build
       dockerfile: Dockerfile
    command: /start-jupyterlab.sh
    working_dir: /opt/workspace
    ports:
       - 8888:8888 # jupyterlab
       - 6006:6006 # tensorboard
    volumes:
      - ./home:/mnt/home:ro                # copying files from 'home' directory to target home directory (/root)
      - ./home/.jupyter:/root/.jupyter:rw  # jupyter settings, we want to keep them between container resets
      - ./workspace:/opt/workspace:rw      # this maps your projects folder
      # - ../../projects:/opt/workspace:rw # example: local mapping (stellars)

# EOF
