# ----------------------------------------------------------------------------------------
#
#   Jupyterlab setup 
#
#   Jupyter Lab - http://localhost:8888
#   Tensorboard - http://localhost:6006
#
# ----------------------------------------------------------------------------------------

services:
  # run jupyterlab on a local port 8888
  # without any authentication
  jupyterlab:
    container_name: lab
    hostname: lab
    image: stellars/stellars-jupyterlab-ds:latest
    build:
       context: build
       dockerfile: Dockerfile
    command: /start-jupyterlab.sh
    environment:
       - CONDA_DEFAULT_ENV=base # choices are: base, tensorflow, torch
       - JUPYTERLAB_SERVER_IP=*
       - JUPYTERLAB_SERVER_TOKEN=
    ports:
       - 8888:8888 # jupyterlab
       - 8000:8000 # jupyterhub
       - 8001:8001 # jupyterhub proxy
       - 6006:6006 # tensorboard
       - 5000:5000 # mlflow
    volumes:
      - home:/home                    # jupyterlab user directory persistence
      - workspace:/home/lab/workspace # user projects workspace volume persistence
      - certs:/mnt/certs              # persistent certificate store for ssl

volumes:
  workspace:
  certs:
  home:

# EOF
