# ----------------------------------------------------------------------------------------
#
#   Jupyterlab setup with NVIDIA GPU support
#
#   Jupyter Lab - http://localhost:8888
#   Tensorboard - http://localhost:6006
#
# ----------------------------------------------------------------------------------------
version: "3"

services:
  # run jupyterlab on a local port 8888
  # without any authentication
  jupyterlab:
    container_name: jupyterlab
    hostname: jupyterlab-nvidia
    image: stellars/stellars-jupyterlab-ds:latest
    build:
       context: build
       dockerfile: Dockerfile
    command: /start-jupyter.sh
    working_dir: /home/jupyterlab
    ports:
       - 8888:8888 # jupyterlab
       - 6006:6006 # tensorboard
       - 5000:5000 # mlflow
    volumes:
      - ./home:/mnt/home:ro   # copying files from 'home' directory to target home directory
      - ./home/.jupyter:/home/jupyterlab/.jupyter:rw  # jupyter settings, making sure it is synced
      - ./workspace:/mnt/workspace:rw      # this maps your projects folder
      # - ../../projects:/mnt/workspace:rw # example: local mapping (stellars)
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  # verifies if GPU is available and enabled
  nvidia-test:
    image: nvidia/cuda:11.0.3-base-ubuntu20.04
    container_name: nvidia-test
    command: nvidia-smi
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

# EOF
