# ----------------------------------------------------------------------------------------
#
#   Jupyter Lab - http://localhost:8888
#
# ----------------------------------------------------------------------------------------
version: "3"

services:
  # run jupyterlab on a local port 8888
  # without any authentication
  jupyterlab:
    container_name: stellars-jupyterlab-ds
    hostname: stellars-jupyterlab-ds
    image: stellars/stellars-jupyterlab-ds:latest
    build:
       context: build
       dockerfile: Dockerfile
    command: /start-jupyterlab.sh
    working_dir: /opt/workspace
    ports:
       - 8888:8888
    volumes:
      - ./home:/mnt/home                # copying files from 'home' directory to target home directory (/root)
      - ./home/.jupyter:/root/.jupyter  # jupyter settings, we want to keep them between container resets
      - ../../projects:/opt/workspace   # my local mapping (stellars)
      # - ./workspace:/opt/workspace    # this maps your projects folder

# EOF
